Install live server
franreyn/pimaonline-stratacss pull request #4
Opened 2024-02-21 23:47 UTC by aphan-webdev

- Install and configure `live-server` and `html-webpack-plugin` packages
- Create placeholder `index.html` in `src` for testing

2024-03-11 21:20 UTC, aphan-webdev commented on vite.config.js
It turns out there are no manual configurations needed to compile sass. It's built into Vite.

2024-03-19 22:18 UTC, franreyn requested changes
Notes inline.

2024-03-19 22:26 UTC, aphan-webdev commented on package.json
> +    "build": "vite build --emptyOutDir --watch",
@franreyn Ok I think moving the watch feature to serve makes sense. Currently, dev is the main command that does everything. If we want serve to build, watch, and preview, does that eliminate the need for dev?

2024-03-19 22:29 UTC, franreyn commented on package.json
> +    "build": "vite build --emptyOutDir --watch",
Yes it does. We could use dev instead of serve tho, just b/c it's more common and easier to remember. Thoughts?

2024-03-19 22:31 UTC, aphan-webdev commented on package.json
> +    "build": "vite build --emptyOutDir --watch",
Ok sounds good

2024-03-19 22:53 UTC, aphan-webdev commented on package.json
> +    "build": "vite build --emptyOutDir --watch",
@franreyn So it looks like the `--watch` flag only works when added to the `build` script. If I add watch to `dev` it doesn't work and if I add it to `serve` that doesn't work either.

2024-03-19 23:42 UTC, franreyn requested changes

2024-03-19 23:42 UTC, franreyn commented on package.json
> +    "build": "vite build --emptyOutDir --watch",
Looks like you may have forgotten to remove `--watch` from `build`.

2024-03-19 23:53 UTC, franreyn approved these changes
Thank you.

2024-03-19 23:53 UTC, merged